export const CREATE_CATEGORY = 'CATEGORY/CREATE_CATEGORY';
export const CREATE_SALARY = 'SALARY/CREATE_SALARY';
export const CREATE_LOCATION = 'LOCATION/CREATE_LOCATION';
export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_ALERT = 'APP/SHOW_ALERT';
export const HIDE_ALERT = 'APP/HIDE_ALERT';